export const SUGGESTION_SEEDS: string[] = [
  'Reply to outstanding emails',
  'Schedule a dentist appointment',
  'Buy groceries for the week',
  'Pay credit card bill',
  'Renew driver’s licence',
  'Plan weekend trip',
  'Read a chapter of current book',
  'Go for a 30-minute walk',
  'Drink 2 litres of water',
  'Stretch for 10 minutes',
  'Call a friend or family member',
  'Tidy the desk',
  'Empty the dishwasher',
  'Do laundry',
  'Take out the recycling',
  'Water the plants',
  'Review this week’s budget',
  'Back up the laptop',
  'Update the package dependencies',
  'Write a journal entry',
  'Practice a language for 15 minutes',
  'Meal-prep lunches for the week',
  'Book a haircut',
  'Send the birthday card',
  'Renew gym membership',
  'Refill prescription',
  'Clean out the inbox to zero',
  'Cancel the unused subscription',
  'Review and pay this month’s bills',
  'Plan tomorrow’s priorities',
]
