/**
 * Style-doc generator — emits one `docs/styles/<id>.md` per populated
 * `palettes/<id>.description.ts`, plus `docs/styles/INDEX.md` listing
 * populated + missing palettes. Run via `pnpm run gen:style-docs`.
 *
 * The generated docs are committed to the repo so external projects can
 * link to a stable URL. Each doc appends the existing
 * `palettes/<id>.README.md` verbatim inside a `<details>` block — the
 * curated prose stays adjacent without duplicate maintenance.
 *
 * The actual markdown body is rendered by
 * `src/theme/renderStyleDescription.ts` so the SPA per-palette design
 * page emits byte-identical text from the same source.
 */
import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { palettes, type PaletteId } from '../palettes'
import type { StyleDescription } from '../tokens/style-description.contract'
import { renderStyleDescriptionMarkdown } from '../src/theme/renderStyleDescription'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT = path.resolve(__dirname, '..')
const PALETTES_DIR = path.join(ROOT, 'palettes')
const OUT_DIR = path.join(ROOT, 'docs', 'styles')

function readReadme(id: PaletteId): string | undefined {
  const readmePath = path.join(PALETTES_DIR, `${id}.README.md`)
  if (!fs.existsSync(readmePath)) return undefined
  return fs.readFileSync(readmePath, 'utf-8')
}

function renderIndex(populated: PaletteId[], missing: PaletteId[]): string {
  const lines: string[] = []
  lines.push('# Style descriptions — index')
  lines.push('')
  lines.push(
    `${populated.length} of ${populated.length + missing.length} palettes have structured descriptions. Add a \`palettes/<id>.description.ts\` and register it in \`palettes/descriptions.ts\` to populate one.`,
  )
  lines.push('')
  lines.push('## Populated')
  lines.push('')
  for (const id of populated) {
    lines.push(`- [${palettes[id].name}](./${id}.md) — \`${palettes[id].engine}\``)
  }
  lines.push('')
  if (missing.length > 0) {
    lines.push('## Missing')
    lines.push('')
    for (const id of missing) {
      lines.push(`- ${palettes[id].name} — \`${palettes[id].engine}\``)
    }
    lines.push('')
  }
  lines.push('---')
  lines.push('')
  lines.push(
    '_Generated by `scripts/generate-style-docs.ts` — do not edit by hand._',
  )
  return lines.join('\n') + '\n'
}

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true })

  const files = fs
    .readdirSync(PALETTES_DIR, { withFileTypes: true })
    .filter(e => e.isFile() && e.name.endsWith('.description.ts'))
    .map(e => path.join(PALETTES_DIR, e.name))

  const populated: PaletteId[] = []

  for (const file of files) {
    const mod = (await import(pathToFileURL(file).href)) as {
      description?: StyleDescription
    }
    if (!mod.description) {
      console.warn(`skipped: ${path.relative(ROOT, file)} (no \`description\` export)`)
      continue
    }
    const desc = mod.description
    const outPath = path.join(OUT_DIR, `${desc.paletteId}.md`)
    const md = renderStyleDescriptionMarkdown(desc, palettes, readReadme(desc.paletteId))
    fs.writeFileSync(outPath, md, 'utf-8')
    populated.push(desc.paletteId)
    console.log(`wrote: docs/styles/${desc.paletteId}.md`)
  }

  const all = Object.keys(palettes) as PaletteId[]
  const missing = all.filter(id => !populated.includes(id))
  fs.writeFileSync(path.join(OUT_DIR, 'INDEX.md'), renderIndex(populated, missing), 'utf-8')
  console.log(`wrote: docs/styles/INDEX.md (${populated.length} populated, ${missing.length} missing)`)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
