import type { Palette } from '../tokens/semantic.contract'

export const palette: Palette = {
  id: 'flat-classic',
  name: 'Flat / Classic',
  engine: 'flat',
  a11y: 'pass',
  tokens: {
    color: {
      surface: {
        base: '#ffffff',
        raised: '#ffffff',
        sunken: '#f4f5f7',
        overlay: '#ffffff',
        scrim: 'rgba(15, 23, 42, 0.48)',
      },
      content: {
        primary: '#0f172a',
        secondary: '#475569',
        muted: '#64748b',
        inverse: '#ffffff',
        link: '#1d4ed8',
      },
      border: {
        subtle: '#e2e8f0',
        default: '#cbd5e1',
        strong: '#94a3b8',
        focus: '#1d4ed8',
      },
      intent: {
        primary: {
          bg: '#1d4ed8',
          content: '#ffffff',
          border: '#1d4ed8',
          bgHover: '#1e40af',
          bgActive: '#1e3a8a',
        },
        neutral: {
          bg: '#e2e8f0',
          content: '#0f172a',
          border: '#cbd5e1',
          bgHover: '#cbd5e1',
          bgActive: '#94a3b8',
        },
        success: {
          bg: '#15803d',
          content: '#ffffff',
          border: '#166534',
          bgHover: '#166534',
          bgActive: '#14532d',
        },
        warning: {
          bg: '#b45309',
          content: '#ffffff',
          border: '#92400e',
          bgHover: '#92400e',
          bgActive: '#78350f',
        },
        danger: {
          bg: '#b91c1c',
          content: '#ffffff',
          border: '#991b1b',
          bgHover: '#991b1b',
          bgActive: '#7f1d1d',
        },
        info: {
          bg: '#0e7490',
          content: '#ffffff',
          border: '#155e75',
          bgHover: '#155e75',
          bgActive: '#164e63',
        },
      },
    },
    space: {
      '0': '0',
      '1': '4px',
      '2': '8px',
      '3': '12px',
      '4': '16px',
      '5': '24px',
      '6': '32px',
      '7': '48px',
      '8': '64px',
    },
    radius: {
      none: '0',
      sm: '4px',
      md: '6px',
      lg: '10px',
      pill: '999px',
      full: '9999px',
    },
    borderWidth: {
      '0': '0',
      hairline: '1px',
      thin: '1px',
      thick: '2px',
      heavy: '3px',
    },
    elevation: {
      flat: { boxShadow: 'none' },
      low: { boxShadow: '0 1px 2px rgba(15, 23, 42, 0.06)' },
      medium: { boxShadow: '0 4px 6px rgba(15, 23, 42, 0.08), 0 2px 4px rgba(15, 23, 42, 0.04)' },
      high: { boxShadow: '0 10px 15px rgba(15, 23, 42, 0.10), 0 4px 6px rgba(15, 23, 42, 0.05)' },
      overlay: { boxShadow: '0 20px 25px rgba(15, 23, 42, 0.12), 0 10px 10px rgba(15, 23, 42, 0.04)' },
    },
    typography: {
      family: {
        ui: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
        display: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
        mono: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
        pixel: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
        hand: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
      },
      role: {
        display:    { family: 'display', size: '2.5rem',  weight: 700, lineHeight: '1.1', tracking: '-0.02em' },
        title:      { family: 'display', size: '1.75rem', weight: 700, lineHeight: '1.2', tracking: '-0.01em' },
        heading:    { family: 'display', size: '1.25rem', weight: 600, lineHeight: '1.3', tracking: '0' },
        subheading: { family: 'ui',      size: '1rem',    weight: 600, lineHeight: '1.4', tracking: '0' },
        body:       { family: 'ui',      size: '1rem',    weight: 400, lineHeight: '1.5', tracking: '0' },
        label:      { family: 'ui',      size: '0.875rem',weight: 500, lineHeight: '1.4', tracking: '0' },
        caption:    { family: 'ui',      size: '0.75rem', weight: 400, lineHeight: '1.4', tracking: '0.01em' },
        code:       { family: 'mono',    size: '0.875rem',weight: 400, lineHeight: '1.5', tracking: '0' },
      },
    },
    motion: {
      duration: {
        instant: '0ms',
        fast: '120ms',
        base: '200ms',
        slow: '320ms',
      },
      easing: {
        standard: 'cubic-bezier(0.2, 0, 0, 1)',
        in: 'cubic-bezier(0.4, 0, 1, 1)',
        out: 'cubic-bezier(0, 0, 0.2, 1)',
        inOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      decay: '0ms',
    },
    effect: {
      backdropBlur: { none: 'none', sm: 'none', md: 'none', lg: 'none' },
      focusRing: { width: '2px', offset: '2px', color: '#1d4ed8', style: 'solid' },
      overlay: { image: 'none', size: 'auto', blend: 'normal' },
      glow: { radius: '0', color: 'transparent', intensity: 0 },
      pixelGrid: '0',
      strokeVariance: '0',
      paperEdgeColor: 'transparent',
      paperEdgeWidth: '0',
      outline: { color: 'transparent', width: '0' },
      shadowStyle: 'soft',
      // Aurora engine no-op signals. `atmosphereGradient: 'none'` and
      // `luminanceCenter: 'transparent'` mean the engine CSS that paints
      // the gradient and luminance glow at `.palette-root[data-palette^='aurora']`
      // doesn't paint here. `surfaceBy: 'border'` records that this palette
      // demarcates surfaces with a stroke (the default), not with light density.
      atmosphereGradient: 'none',
      luminanceCenter: 'transparent',
      surfaceBy: 'border',
      gridUnitX: '0',
      gridUnitY: '0',
      borderStyle: 'css',
    },
  },
}
